apiVersion: v1
kind: Namespace
metadata:
  name: amrit
---
apiVersion: agill.apps/v1alpha1
kind: AutoKill
metadata:
  name: autokill-namespace
  namespace: amrit
spec:
  deleteNamespaceAfter: 1
  disable: false
  deleteAssociatedHelmReleases: true

