apiVersion: v1
kind: Namespace
metadata:
  name: agill
---
apiVersion: agill.apps/v1alpha1
kind: AutoKill
metadata:
  name: autokill-namespace
  namespace: agill
spec:
  deleteNamespaceAfter: 0
  disable: false
  deleteAssociatedHelmReleases: true
#  tillerNamespace: ops