apiVersion: v1
kind: Namespace
metadata:
  name: agill
---
apiVersion: agill.apps/v1alpha1
kind: AutoKill
metadata:
  name: autokill-namespace
  namespace: agill
spec:
  # hours
  deleteNamespaceAfter: 1
  disable: false
  # deletes ALL associated helm releases
  deleteAssociatedHelmReleases: true
  # tiller-namespace -- defaults to kube-system 
  #tillerNamespace: your-tiller-namespace
